apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "application.name" . }}
  namespace: {{ .Values.application.namespace }}
spec:
  project: {{ .Values.application.project }}
  source:
    repoURL: {{ .Values.application.repoURL }}
    targetRevision: {{ .Values.application.targetRevision }}
    path: {{ .Values.application.path }}
  destination:
    server: {{ .Values.application.destinationServer }}
    namespace: {{ .Values.application.destinationNamespace }}
  syncPolicy:
    automated:
      prune: {{ .Values.application.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.application.syncPolicy.automated.selfHeal }}
    syncOptions:
      - CreateNamespace={{ .Values.application.syncPolicy.syncOptions.createNamespace }}
